name: Robot Framework CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Instalar navegador e drivers
      run: |
        sudo apt update
        sudo apt install -y chromium-browser chromium-chromedriver
        export PATH=$PATH:/usr/lib/chromium-browser/

    - name: Executar testes
      run: |
        robot -d logs tests/