name: Robot Framework CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: pip install -r requirements.txt

    - name: Instalar navegador e drivers
      run: |
        sudo apt update
        sudo apt install -y wget unzip google-chrome-stable jq
        CHROME_VERSION=$(google-chrome-stable --version | grep -oP '\d+\.\d+\.\d+' | head -1)
        echo "Versão do Google Chrome detectada: $CHROME_VERSION"

        DRIVER_URL=$(wget -qO- https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | \
          jq -r --arg ver "$CHROME_VERSION" '.channels.Stable.downloads.chromedriver[] | select(.platform=="linux64") | .url')

        echo "Baixando ChromeDriver de: $DRIVER_URL"
        wget "$DRIVER_URL" -O chromedriver.zip
        unzip chromedriver.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        chmod +x /usr/local/bin/chromedriver
        chromedriver --version





    - name: Executar testes
      run: robot -d logs tests/
